# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-20 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_active_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='can_adjust',
            field=models.BooleanField(default=True, help_text='Define si se puede ajustar la prediccion en el proyecto.'),
        ),
        migrations.AddField(
            model_name='project',
            name='can_dowload_report',
            field=models.BooleanField(default=True, help_text='Define si el usuario final puede descargar el reporte.'),
        ),
        migrations.AddField(
            model_name='project',
            name='can_send_report',
            field=models.BooleanField(default=True, help_text='Define si el usuario final puede enviar el reporte por email a su superior.'),
        ),
    ]
