# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-20 21:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190320_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
