# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-27 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_admin_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='adjustment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Predicción ajustada'),
        ),
        migrations.AddField(
            model_name='project',
            name='ceve_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Centro de venta ID'),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='project',
            name='in_stock',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Inventario'),
        ),
        migrations.AddField(
            model_name='project',
            name='prediction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Predicción'),
        ),
        migrations.AddField(
            model_name='project',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Producto ID'),
        ),
        migrations.AddField(
            model_name='project',
            name='safety_stock',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Safety stock'),
        ),
        migrations.AddField(
            model_name='project',
            name='transitos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transitos'),
        ),
    ]
