# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-27 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190327_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beds',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pedido en camas'),
        ),
        migrations.AddField(
            model_name='project',
            name='pallets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pedido en tarimas'),
        ),
    ]
