# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-27 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190327_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='transitos',
            new_name='transits',
        ),
    ]
