# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-18 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=600, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
                ('picture', models.ImageField(upload_to='')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('trial', 'trial'), ('activationPending', 'activationPending')], default='active', max_length=255, verbose_name='status')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
        ),
    ]
