# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-22 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('datasetrows', '0002_auto_20190219_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrow',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Route'),
        ),
    ]
