# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-22 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasetrows', '0003_datasetrow_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetrow',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cycles.Cycle'),
        ),
        migrations.AlterField(
            model_name='datasetrow',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='periods.Period'),
        ),
    ]
