# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-16 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'permissions': (('can_adjust_sales', 'Can adjust sales'), ('can_adjust_last_order', 'Can adjust last order')), 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
