# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-22 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190416_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_edit',
        ),
    ]
