# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-06 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190422_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'permissions': (('can_adjust_sales', 'Can adjust sales'), ('can_adjust_last_order', 'Can adjust last order'), ('can_add_order', 'Can add order'), ('can_send_email', 'Can send email')), 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
