version: '3'
services:
  admin:
    restart: always
    build: 
      context: .
      dockerfile: DockerfileNginxAdmin
    ports:
      - "3001:80"
  web:
    restart: always
    build: 
      context: .
      dockerfile: DockerfileNginxApp
    ports:
      - "3002:80"
  api:
    restart: always
    build: .
    ports:
     - "3000:3000"
     - "4000:4000"
     - "5001:5000"
    links:
      - mongodb
      - redisdb
    depends_on:
      - mongodb    
      - redisdb
    env_file:
      - .env
  redisdb:
    restart: always
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mongodb:
    restart: always
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet