version: '2.3'
services:
  web:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    cpu_shares: 50
    mem_limit: 2000M
    mem_reservation: 500m
    env_file:
      - .env
  python:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
     - "8000:8000"
    links:
      - redisdb
      - postgresdb
    depends_on:
      - redisdb
      - postgresdb
    cpu_shares: 20
    cpus: 2
    mem_limit: 5000M
    mem_reservation: 2000m
    env_file:
      - .env
    volumes:
      - /data/db:/data/db
      - /data/media/uploads:/app/media/uploads
  redisdb:
    restart: always
    image: "redis:alpine"
    ports:
      - "6379:6379"
    cpu_shares: 100
    cpus: 1
    mem_limit: 1000M
    mem_reservation: 1000m
  postgresdb:
    restart: always
    image: "postgres:11.1-alpine"
    ports:
      - "5432:5432"
    cpu_shares: 100
    cpus: 1
    mem_limit: 6000M
    mem_reservation: 1000m
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: orax
    volumes:
      - /data/postgres:/var/lib/postgresql/data:Z
