# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-18 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('cycle', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='rules.Rule')),
            ],
            options={
                'verbose_name': 'cycle',
                'verbose_name_plural': 'cycles',
            },
        ),
    ]
