# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-18 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('start_date', models.DateTimeField()),
                ('cycle_duration', models.PositiveIntegerField()),
                ('cycle', models.CharField(max_length=25, verbose_name='cycle')),
                ('period_duration', models.PositiveIntegerField()),
                ('period', models.CharField(max_length=25, verbose_name='period')),
                ('season', models.PositiveIntegerField()),
                ('available_cycles', models.PositiveIntegerField()),
                ('take_start', models.BooleanField(default=True)),
                ('consolidation', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
            options={
                'verbose_name_plural': 'rules',
                'verbose_name': 'rule',
            },
        ),
    ]
