# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-18 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('sales_centers', '0001_initial'),
        ('periods', '0001_initial'),
        ('datasets', '0001_initial'),
        ('products', '0001_initial'),
        ('channels', '0001_initial'),
        ('cycles', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('status', models.CharField(choices=[('created', 'created'), ('processing', 'processing'), ('done', 'done'), ('unmodified', 'unmodified'), ('sendingChanges', 'sendingChanges'), ('adjusted', 'adjusted'), ('error', 'error')], max_length=255, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.Channel')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.Cycle')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Dataset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periods.Period')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('sale_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_centers.SaleCenter')),
            ],
            options={
                'verbose_name_plural': 'dataset rows',
                'verbose_name': 'dataset row',
            },
        ),
    ]
