# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-19 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetrows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrow',
            name='adjustment',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetrow',
            name='prediction',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
