# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-25 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetrows', '0005_auto_20190222_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrow',
            name='refund',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetrow',
            name='sale',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
