# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-26 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetrows', '0007_datasetrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetrow',
            name='refund',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datasetrow',
            name='sale',
            field=models.IntegerField(default=0),
        ),
    ]
