# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '__first__'),
        ('servers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Domain name, for example goole.com', max_length=60)),
                ('provider', models.ForeignKey(help_text='Provider who sold the domain. For example Azure, Google..', on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='providers.Provider')),
                ('server', models.ForeignKey(help_text='Server where the domain is pointing', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='servers.Server')),
            ],
        ),
    ]
