# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-22 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='separated_by',
            field=models.CharField(default=',', max_length=1, verbose_name='separated_by'),
        ),
    ]
