# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-14 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='type',
            field=models.CharField(choices=[('products', 'products'), ('routes', 'routes')], max_length=255, verbose_name='type'),
        ),
    ]
