# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-14 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_auto_20190314_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='type',
            field=models.CharField(choices=[('products', 'products'), ('sales_centers', 'sales_centers')], max_length=255, verbose_name='type'),
        ),
    ]
