# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-26 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_batch_separated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='type',
            field=models.CharField(choices=[('products', 'products'), ('routes', 'routes'), ('sales_centers', 'sales_centers')], max_length=255, verbose_name='type'),
        ),
    ]
