# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-28 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_auto_20190226_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='type',
            field=models.CharField(choices=[('products', 'products'), ('routes', 'routes'), ('sales_centers', 'sales_centers'), ('prices', 'prices'), ('quota', 'quota')], max_length=255, verbose_name='type'),
        ),
    ]
