# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190320_1741'),
        ('batch', '0003_auto_20190314_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
    ]
