# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A server can have one or more environments. For example: Testing, CI, Demo, Production, etc', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The key to identify the server. For example turing-server.', max_length=60)),
                ('ip_v4', models.CharField(help_text='The IP V4 of server', max_length=15)),
                ('ip_v6', models.CharField(blank=True, help_text='The IP V6 of server', max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='environment',
            name='server',
            field=models.ManyToManyField(related_name='environments', to='servers.Server'),
        ),
    ]
