# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-17 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='A', help_text='Tipo de producto. A, B o C.', max_length=3, verbose_name='product type'),
        ),
    ]
