# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-18 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        ('organizations', '0001_initial'),
        ('datasets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=600, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('status', models.CharField(choices=[('empty', 'empty'), ('processing', 'processing'), ('ready', 'ready'), ('reviewing', 'reviewing'), ('pendingRows', 'pendingRows'), ('adjustment', 'adjustment'), ('conciliating', 'conciliating'), ('conciliatingForecast', 'conciliatingForecast'), ('cloning', 'cloning'), ('updating-rules', 'updating-rules'), ('pending-configuration', 'pending-configuration')], max_length=255, verbose_name='status')),
                ('cycle_status', models.CharField(choices=[('empty', 'empty'), ('consolidation', 'consolidation'), ('forecastCreation', 'forecastCreation'), ('rangeAdjustmentRequest', 'rangeAdjustmentRequest'), ('rangeAdjustment', 'rangeAdjustment'), ('salesUpload', 'salesUpload')], max_length=255, verbose_name='cycle status')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('active_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_datasets', to='datasets.Dataset')),
                ('main_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_datasets', to='datasets.Dataset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Rule')),
            ],
            options={
                'verbose_name_plural': 'projects',
                'verbose_name': 'project',
            },
        ),
    ]
