# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-14 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bed',
            field=models.IntegerField(default=1, help_text='Cantidad de cupos para llenar una cama.'),
        ),
        migrations.AddField(
            model_name='product',
            name='pallet',
            field=models.IntegerField(default=1, help_text='Cantidad de camas para llenar una tarima.'),
        ),
    ]
