# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-28 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
