# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-28 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quota',
            field=models.IntegerField(default=1, help_text='Cantidad de productos para llenar un corrugado.'),
        ),
    ]
