# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-14 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190314_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bed',
            field=models.IntegerField(default=1, help_text='Cantidad de corrugados para llenar una cama.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pallet',
            field=models.IntegerField(default=1, help_text='Cantidad de corrugados para llenar una tarima.'),
        ),
    ]
