# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-19 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import orax.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', orax.users.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
    ]
