# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-20 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_centers', '0002_salecenter_project'),
        ('users', '0003_user_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='sale_center',
        ),
        migrations.AddField(
            model_name='user',
            name='sale_center',
            field=models.ManyToManyField(to='sales_centers.SaleCenter'),
        ),
    ]
