# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-21 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190320_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
    ]
