# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-21 18:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_can_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
