# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-27 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_centers', '0001_initial'),
        ('users', '0005_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_centers.SaleCenter'),
        ),
    ]
