# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-02 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='adjustment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='admin_emails',
        ),
        migrations.RemoveField(
            model_name='project',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='project',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pallets',
        ),
        migrations.RemoveField(
            model_name='project',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='project',
            name='safety_stock',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='transits',
        ),
    ]
