# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-09 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190402_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bucket_folder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AWS BUCKET FOLDER'),
        ),
        migrations.AddField(
            model_name='project',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AWS BUCKET NAME'),
        ),
    ]
