# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-17 17:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190409_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
