# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-17 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_report_columns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='can_dowload_report',
            new_name='can_download_report',
        ),
    ]
