# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-22 18:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190417_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dynamic_columns_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='report_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
