# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Java, Python, Jenkins, Intertours project, etc.', max_length=100)),
                ('version', models.PositiveIntegerField(help_text='For example the python version is 3.6, the JDK version is 8, etc')),
                ('source_URL', models.URLField(help_text='URL where the app can be download')),
                ('notes', models.TextField(help_text='Notes about how to install the app or some comment')),
            ],
        ),
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='There are 2 application types, the apps like Python, Java, Jenkins, etc. And the apps wich are developing in IB, like kidzania, Interjet, etc.', max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='The port number, like: 8080, 80 ...', unique=True)),
                ('app', models.ForeignKey(help_text='App wich is using this port', on_delete=django.db.models.deletion.CASCADE, related_name='used_ports', to='apps.App')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='type',
            field=models.ForeignKey(help_text='Application type, for example program or an IB project', on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='apps.AppType'),
        ),
    ]
