# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of provider. For example Google, Azure ...', max_length=100)),
            ],
        ),
    ]
