# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-20 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='rules.Rule'),
        ),
    ]
