# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='documentation',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='documentationtype',
            options={'verbose_name': 'Document type', 'verbose_name_plural': 'Document types'},
        ),
        migrations.AddField(
            model_name='answer',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='documentation.Documentation'),
            preserve_default=False,
        ),
    ]
